INSTDIR	= /usr/local

all:

clean:
	rm -f *.tmp *.o *.b

install:
	install -d $(INSTDIR)/lib/pic16/include
	install -c pic12c5xx.h $(INSTDIR)/lib/pic16/include
	install -c pic12c5xx.inc $(INSTDIR)/lib/pic16/include
